== ARCHANGEL

> The ARCHANGEL project proposes to deliver *long-term sustainability of digital archives* through *new technologies* that will ensure both *accessibility and integrity of digital archives*

[NOTE.speaker]
--
Because I came in a bit later, I don't know who came up with the name Archangel, or why it's stylised in all-capitals. That makes it sound quite portentous and serious and actually a little bit creepy somehow, which is a shame because Archangel is explicitly about trust.
--

== ARCHANGEL


> Archangel is a collaboration between the University of Surrey CVSSP, The National Archive, and The Open Data Institute.

> It's funded by Research Councils UK's Digital Economy Programme through the EPSRC (the Engineering and Physical Sciences Research Council


[NOTE.speaker]
--
Archangel is a collaboration between the University of Surrey CVSSP - Centre for Vision, Speech, & Signal Processing, The National Archive, and The Open Data Institute.

It's funded by Research Councils UK's Digital Economy Programme through the the Engineering and Physical Sciences Research Council

I don't know if I have to tell you that, but I've a feeling we tick something off on a "what we did to puplicise the project" scoresheet if I do. It also means that, right at the moment, the entirity of my income is a drain on the public purse.  Thank you all.
--

== ARCHANGEL

> The ARCHANGEL project proposes to deliver *long-term sustainability of digital archives* through *new technologies* that will ensure both *accessibility and integrity of digital archives*

[NOTE.speaker]
--
So anyway, the ARCHANGEL project proposes to deliver *long-term sustainability of digital archives* through *new technologies* that will ensure both *accessibility and integrity of digital archives*

What do we mean?

By long term sustainability, we mean we want to try and ensure that public trust in the archive can be maintained, not just now, but for years, decades into the future.  We're calling out digital archives, because it's ony a two year project :) Can't cover everything!  And we going to do this through the application of new technologies ...
--

== ARCHANGEL

And those new technologies are?
[%step]
* The Blockchain

* Machine Learning

[NOTE.speaker]
--
And those new technologies are?

The blockchain, or at least a blockchain, or, more properly a distributed ledger technogoly.

And machine learning.

Jesus, could it get any more hipster?

Anyone care to have a stab at where we're doing with those particular "new technologies"?
--
